### ISSUE TITLE
TODO checklist

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/air-monitor#1]
Items as they come up:

-----
_TODO:_

_New in 2026_

**For Will -- Do this on a separate branch.**

_Items finished by 2026-06-09_

- [x] Review code and make incremental bug fixes and adjustments as you see fit (06/05)
- [x] Spend a day or more learning how to use arquero (06/05)
- [x] Add/update `CLAUDE.md` file and `.claude/prompts/` from `airfire-pdf-service` repo (06/05)
- [x] Create `CLAUDE_ARCHITECTURE.md` and `CLAUDE_UPDATES.md` files. (06/05)
_New in 2025_

——

- [ ] Include named and default exports. (7/21/25)
```
class Monitor { ... }
export { Monitor };
export default Monitor;
```
- [ ] Handle missing ids in `getMetadata()` (9/19/25) 
https://chatgpt.com/g/g-p-687eab1f8b8c81919c2244d9d06206ae-monitoring-v5/c/68cdd00a-2528-8321-9107-33e500fdc9e9

——

_Items finished on 2024-07-09_

- [x] `monitor_combine()` trims all monitors to the shortest time axis. It should pad to the longest. (11/14)
